# Generated by Django 6.0.7 on 2026-08-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={},
        ),
    ]
